# Generated by Django 3.2.8 on 2022-09-19 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Client_Name', models.CharField(max_length=100)),
                ('Job_Description', models.CharField(max_length=100)),
                ('Reocurring', models.BooleanField(default=False)),
                ('Phone_Number', models.CharField(max_length=100)),
                ('Job_address', models.CharField(max_length=100)),
                ('Hrs_Allocated', models.IntegerField()),
                ('Frequency', models.CharField(max_length=100)),
                ('Case_Manager', models.CharField(max_length=100)),
                ('Contractor', models.CharField(max_length=100)),
                ('Assign_to', models.CharField(max_length=100)),
                ('Last_Booking_Date', models.DateField()),
                ('New_Booking_Date', models.DateField()),
                ('Time_confirmed', models.BooleanField(default=False)),
                ('Status', models.CharField(max_length=100)),
                ('Comments', models.CharField(max_length=100)),
            ],
        ),
    ]
