# Generated by Django 3.2.8 on 2022-09-19 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_tracker', '0002_auto_20220919_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='Last_Booking_Date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='New_Booking_Date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='Reocurring',
            field=models.CharField(max_length=100),
        ),
    ]
