# Generated by Django 3.2.8 on 2023-03-03 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_tracker', '0004_auto_20230302_2114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='Assign_to',
            new_name='assign_to',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='Case_Manager',
            new_name='case_manager',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='Client_Name',
            new_name='client_name',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='Comments',
            new_name='comments',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='Contractor',
            new_name='contractor',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='Frequency',
            new_name='frequency',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='Job_address',
            new_name='job_address',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='Job_Description',
            new_name='job_description',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='Last_Booking_Date',
            new_name='last_booking_date',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='New_Booking_Date',
            new_name='new_booking_date',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='Phone_Number',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='Reocurring',
            new_name='reoccurring',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='Status',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='Time_confirmed',
            new_name='time_confirmed',
        ),
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
