# Generated by Django 3.2.8 on 2023-03-03 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_tracker', '0005_auto_20230303_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='last_booking_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='new_booking_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='time_confirmed',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
