# Generated by Django 3.2.8 on 2021-10-16 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('value', models.FloatField()),
                ('date', models.DateTimeField()),
                ('category', models.CharField(max_length=64)),
                ('repetitive', models.BooleanField(default=False)),
                ('details', models.CharField(max_length=64)),
                ('user_id', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'balances',
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('value', models.FloatField()),
                ('date', models.DateTimeField()),
                ('category', models.CharField(max_length=64)),
                ('repetitive', models.BooleanField(default=False)),
                ('details', models.CharField(max_length=64)),
                ('user_id', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'incomes',
            },
        ),
        migrations.CreateModel(
            name='Outcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('value', models.FloatField()),
                ('date', models.DateTimeField()),
                ('category', models.CharField(max_length=64)),
                ('repetitive', models.BooleanField(default=False)),
                ('details', models.CharField(max_length=64)),
                ('user_id', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'outcomes',
            },
        ),
    ]
