# Generated by Django 3.2.8 on 2021-10-16 06:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('my_finances', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balance',
            name='repetitive',
        ),
        migrations.RemoveField(
            model_name='outcome',
            name='repetitive',
        ),
        migrations.AddField(
            model_name='balance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='balance',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='income',
            name='repetition_interval',
            field=models.PositiveSmallIntegerField(choices=[(1, 'NONE'), (2, 'DAYLY'), (3, 'WEEKLY'), (4, 'FORNIGHTLY'), (5, 'MONTHLY'), (6, 'BIANNUALLY'), (7, 'YEARLY')], default=1),
        ),
        migrations.AddField(
            model_name='income',
            name='repetition_time',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='outcome',
            name='repetition_interval',
            field=models.PositiveSmallIntegerField(choices=[(1, 'NONE'), (2, 'DAYLY'), (3, 'WEEKLY'), (4, 'FORNIGHTLY'), (5, 'MONTHLY'), (6, 'BIANNUALLY'), (7, 'YEARLY')], default=1),
        ),
        migrations.AddField(
            model_name='outcome',
            name='repetition_time',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='balance',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(1, 'CURRENT'), (2, 'SAVINGS'), (3, 'CASH')]),
        ),
        migrations.AlterField(
            model_name='balance',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='income',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(1, 'SALARY'), (2, 'BONUS'), (3, 'GIFT'), (4, 'OTHER')]),
        ),
        migrations.AlterField(
            model_name='income',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='outcome',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(1, 'SALARY'), (2, 'BONUS'), (3, 'INSURANCE'), (4, 'TRANSPORTATION'), (5, 'ENTERTAINMENT'), (6, 'GIFTS'), (7, 'TAXES'), (8, 'SAVINGS'), (9, 'INVESMENT')]),
        ),
        migrations.AlterField(
            model_name='outcome',
            name='date',
            field=models.DateField(),
        ),
    ]
