# Generated by Django 3.2.8 on 2021-10-29 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_finances', '0003_auto_20211016_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='comment_char',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='income',
            name='comment_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='income',
            name='repetition_interval',
            field=models.PositiveSmallIntegerField(choices=[(1, 'NONE'), (2, 'DAILY'), (3, 'WEEKLY'), (4, 'FORNIGHTLY'), (5, 'MONTHLY'), (6, 'BIANNUALLY'), (7, 'YEARLY')], default=1),
        ),
        migrations.AlterField(
            model_name='outcome',
            name='repetition_interval',
            field=models.PositiveSmallIntegerField(choices=[(1, 'NONE'), (2, 'DAILY'), (3, 'WEEKLY'), (4, 'FORNIGHTLY'), (5, 'MONTHLY'), (6, 'BIANNUALLY'), (7, 'YEARLY')], default=1),
        ),
    ]
