# Generated by Django 3.2.8 on 2022-03-13 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_finances', '0006_auto_20211111_1538'),
    ]

    operations = [
        migrations.RenameField(
            model_name='balance',
            old_name='details',
            new_name='comments',
        ),
        migrations.AddField(
            model_name='balance',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'CURRENT'), (2, 'SAVINGS'), (3, 'CASH'), (4, 'INVESTMENT')], default=1),
        ),
    ]
